# Generated by Django 2.1.5 on 2020-02-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
